name: SensuFlow Resource Publish

##
# You'll want to review the GitHub Action 'on' conditions to match your policy
##
on:
  push:
    # Run for any commit or tag pushed to the main branch of the github repository
    branches: [ main ]
    # Run when any tag is pushed to the github repository
    tags: ['**'] 
jobs:
  # Define the SensuFlow workflow job 
  SensuFlow:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checks-out your repository
    - name: Checkout
      uses: actions/checkout@v2

    # Step 2: use the versioned sensu/sensuflow action 
    - name: Sensuflow with required settings
      uses: sensu/sensu-flow@0.6.0
      with:
        # Required configuration
        # Please make use of GitHub secrets for sensitive information 
        sensu_api_url: ${{ secrets.SENSU_API_URL }}
        sensu_api_key: ${{ secrets.SENSU_API_KEY }}
        # Optional configuration, if not present defaults will be used
        namespaces_dir: .sensu/namespaces
        namespaces_file: .sensu/cluster/namespaces.yaml
        matching_label: "sensu.io/workflow"
        matching_condition: "== 'sensu-flow'"
        managed_resources: "assets,checks,entities,events,filters,handlers,hooks,mutators,pipelines,silenced,secrets/v1.Secret"
        #managed_resources: "assets,checks,entities,events,filters,handlers,hooks,mutators,pipelines,silenced,secrets/v1.Secret,bsm/v1.RuleTemplate,bsm/v1.ServiceComponent,pipeline/v1.TCPStreamHandler,pipeline/v1.SumoLogicMetricsHandler"
        # The full list of configuration options can be found at https://github.com/sensu/sensu-flow 
