name: SensuFlow CI Test

##
# You'll want to review the GitHub Action 'on' conditions to match your policy
##
on:
  push:
    tags:
      - '**' # run on any tag push
    branches: [ '**' ]  # run on push to main
  pull_request:
    branches: [ main ] # run on any PR against main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sensuflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    - name: prep apt
      run: >-
        apt update && apt install -y
        apt-transport-https 
        ca-certificates 
        curl 
        gnupg 
        net-tools
        lsb-release
    - name: get docker gpg
      run: >-
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - name: setup docker apt source
      run: >-
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
        | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: install docker
      run: >-
        DEBIAN_FRONTEND=noninteractive apt update && apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    # Run a locally available sensu-backend service from a docker container
    - name: Run local sensu-backend using docker
      run: >-
        docker run 
        -d
        --name sensu-backend
        --hostname sensu-backend 
        --network ${{ job.container.network }}  
        -e SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${{ ci-sensu-test-admin }} 
        -e SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${{ ci-sensu-test-admin }}
        -e SENSU_BACKEND_CLUSTER_ADMIN_API_KEY=${{ secrets.SENSU_API_KEY }}
        sensu/sensu:latest
        sensu-backend start
    - name: wait for sensu-backend
      run: curl --head -X GET --retry 10 --retry-connrefused --retry-delay 2 http://sensu-backend:8080/health

    # Test SensuFlow action against test backend container
    # Note: Make sure the configuration here matches the release workflow.
    - name: Test Sensuflow
      uses: sensu/sensu-flow@0.6.0
      id: matching-label-with-dash
      with:
        sensu_api_url: http://sensu-backend:8080
        sensu_api_key: ${{ secrets.SENSU_API_KEY }} 
        namespaces_dir: .sensu/namespaces/
        namespaces_file: .sensu/cluster/namespaces.yaml
        matching_label: "sensu.io/workflow"
        matching_condition: "== 'sensu-flow'"

